// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabalho_Final.Data;

#nullable disable

namespace Trabalho_Final.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20221026002319_DbVersion3")]
    partial class DbVersion3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Trabalho_Final.Models.Cartao", b =>
                {
                    b.Property<int>("Nr_Cartao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Nr_Cliente")
                        .HasColumnType("int");

                    b.Property<float>("Saldo")
                        .HasColumnType("float");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Nr_Cartao");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("Trabalho_Final.Models.Cliente", b =>
                {
                    b.Property<int>("NrCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NrContribuinte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("SaldoDisponivel")
                        .HasColumnType("float");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ValidadeSaldo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("NrCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Trabalho_Final.Models.Mensagem", b =>
                {
                    b.Property<int>("Id_Mensagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data_Envio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Destino")
                        .HasColumnType("int");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.HasKey("Id_Mensagem");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("Trabalho_Final.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
